COUNTRY_CODES = [
['Afghanistan','AF'],
['Albania','AL'],
['Algeria','DZ'],
['American','AS Samoa'],
['Andorra','AD'],
['Angola','AO'],
['Anguilla','AI'],
['Antarctica','AQ'],
['Antigua','AG And Barbuda'],
['Argentina','AR'],
['Armenia','AM'],
['Aruba','AW'],
['Australia','AU'],
['Austria','AT'],
['Azerbaijan','AZ'],
['Bahamas','BS'],
['Bahrain','BH'],
['Bangladesh','BD'],
['Barbados','BB'],
['Belarus','BY'],
['Belgium','BE'],
['Belize','BZ'],
['Benin','BJ'],
['Bermuda','BM'],
['Bhutan','BT'],
['Bolivia','BO'],
['Bosnia','BA And Herzegovina'],
['Botswana','BW'],
['Bouvet','BV Island'],
['Brazil','BR'],
['British','IO Indian Ocean Territory'],
['Brunei','BN'],
['Bulgaria','BG'],
['Burkina','BF Faso'],
['Burundi','BI'],
['Cambodia','KH'],
['Cameroon','CM'],
['Canada','CA'],
['Cape','CV Verde'],
['Cayman','KY Islands'],
['Central','CF African Republic'],
['Chad','TD'],
['Chile','CL'],
['China','CN'],
['Christmas','CX Island'],
['Cocos','CC (Keeling) Islands'],
['Columbia','CO'],
['Comoros','KM'],
['Congo','CG'],
['Cook','CK Islands'],
['Costa','CR Rica'],
['Cote','CI D\'Ivorie (Ivory Coast)'],
['Croatia','HR (Hrvatska)'],
['Cuba','CU'],
['Cyprus','CY'],
['Czech','CZ Republic'],
['Democratic','CD Republic Of Congo (Zaire)'],
['Denmark','DK'],
['Djibouti','DJ'],
['Dominica','DM'],
['Dominican','DO Republic'],
['East','TP Timor'],
['Ecuador','EC'],
['Egypt','EG'],
['El','SV Salvador'],
['Equatorial','GQ Guinea'],
['Eritrea','ER'],
['Estonia','EE'],
['Ethiopia','ET'],
['Falkland','FK Islands (Malvinas)'],
['Faroe','FO Islands'],
['Fiji','FJ'],
['Finland','FI'],
['France','FR'],
['France','FX], Metropolitan'],
['French','GF Guinea'],
['French','PF Polynesia'],
['French','TF Southern Territories'],
['Gabon','GA'],
['Gambia','GM'],
['Georgia','GE'],
['Germany','DE'],
['Ghana','GH'],
['Gibraltar','GI'],
['Greece','GR'],
['Greenland','GL'],
['Grenada','GD'],
['Guadeloupe','GP'],
['Guam','GU'],
['Guatemala','GT'],
['Guinea','GN'],
['Guinea','GW-Bissau'],
['Guyana','GY'],
['Haiti','HT'],
['Heard','HM And McDonald Islands'],
['Honduras','HN'],
['Hong','HK Kong'],
['Hungary','HU'],
['Iceland','IS'],
['India','IN'],
['Indonesia','ID'],
['Iran','IR'],
['Iraq','IQ'],
['Ireland','IE'],
['Israel','IL'],
['Italy','IT'],
['Jamaica','JM'],
['Japan','JP'],
['Jordan','JO'],
['Kazakhstan','KZ'],
['Kenya','KE'],
['Kiribati','KI'],
['Kuwait','KW'],
['Kyrgyzstan','KG'],
['Laos','LA'],
['Latvia','LV'],
['Lebanon','LB'],
['Lesotho','LS'],
['Liberia','LR'],
['Libya','LY'],
['Liechtenstein','LI'],
['Lithuania','LT'],
['Luxembourg','LU'],
['Macau','MO'],
['Macedonia','MK'],
['Madagascar','MG'],
['Malawi','MW'],
['Malaysia','MY'],
['Maldives','MV'],
['Mali','ML'],
['Malta','MT'],
['Marshall','MH Islands'],
['Martinique','MQ'],
['Mauritania','MR'],
['Mauritius','MU'],
['Mayotte','YT'],
['Mexico','MX'],
['Micronesia','FM'],
['Moldova','MD'],
['Monaco','MC'],
['Mongolia','MN'],
['Montserrat','MS'],
['Morocco','MA'],
['Mozambique','MZ'],
['Myanmar','MM (Burma)'],
['Namibia','NA'],
['Nauru','NR'],
['Nepal','NP'],
['Netherlands','NL'],
['Netherlands','AN Antilles'],
['New','NC Caledonia'],
['New','NZ Zealand'],
['Nicaragua','NI'],
['Niger','NE'],
['Nigeria','NG'],
['Niue','NU'],
['Norfolk','NF Island'],
['North','KP Korea'],
['Northern','MP Mariana Islands'],
['Norway','NO'],
['Oman','OM'],
['Pakistan','PK'],
['Palau','PW'],
['Panama','PA'],
['Papua','PG New Guinea'],
['Paraguay','PY'],
['Peru','PE'],
['Philippines','PH'],
['Pitcairn','PN'],
['Poland','PL'],
['Portugal','PT'],
['Puerto','PR Rico'],
['Qatar','QA'],
['Reunion','RE'],
['Romania','RO'],
['Russia','RU'],
['Rwanda','RW'],
['Saint','SH Helena'],
['Saint','KN Kitts And Nevis'],
['Saint','LC Lucia'],
['Saint','PM Pierre And Miquelon'],
['Saint','VC Vincent And The Grenadines'],
['San','SM Marino'],
['Sao','ST Tome And Principe'],
['Saudi','SA Arabia'],
['Senegal','SN'],
['Seychelles','SC'],
['Sierra','SL Leone'],
['Singapore','SG'],
['Slovak','SK Republic'],
['Slovenia','SI'],
['Solomon','SB Islands'],
['Somalia','SO'],
['South','ZA Africa'],
['South','GS Georgia And South Sandwich Islands'],
['South','KR Korea'],
['Spain','ES'],
['Sri','LK Lanka'],
['Sudan','SD'],
['Suriname','SR'],
['Svalbard','SJ And Jan Mayen'],
['Swaziland','SZ'],
['Sweden','SE'],
['Switzerland','CH'],
['Syria','SY'],
['Taiwan','TW'],
['Tajikistan','TJ'],
['Tanzania','TZ'],
['Thailand','TH'],
['Togo','TG'],
['Tokelau','TK'],
['Tonga','TO'],
['Trinidad','TT And Tobago'],
['Tunisia','TN'],
['Turkey','TR'],
['Turkmenistan','TM'],
['Turks','TC And Caicos Islands'],
['Tuvalu','TV'],
['Uganda','UG'],
['Ukraine','UA'],
['United','AE Arab Emirates'],
['United','UK Kingdom'],
['United','US States'],
['United','UM States Minor Outlying Islands'],
['Uruguay','UY'],
['Uzbekistan','UZ'],
['Vanuatu','VU'],
['Vatican','VA City (Holy See)'],
['Venezuela','VE'],
['Vietnam','VN'],
['Virgin','VG Islands (British)'],
['Virgin','VI Islands (US)'],
['Wallis','WF And Futuna Islands'],
['Western','EH Sahara'],
['Western','WS Samoa'],
['Yemen','YE'],
['Yugoslavia','YU'],
['Zambia','ZM'],
['Zimbabwe','ZW']
]