development:
  consumer_key: vYh2RJAPyFDn5Ulpy88OCg
  consumer_secret: BnfQcHlAQ3byFuz0QUEDMkRyex9PuAvu4U70b8gW6Fo
  oauth_token: 211486067-BvKdOopbrCZYrVqHBLPerNQYI0nAMFhiwOLx0qMd
  oauth_token_secret: Mp0HqmTJbrbDxzJjJhuz52d93WzyNA3zW55zD9qaU
  callback_url: http://demax.kicks-ass.org:3001/connectors/twitter/callback
  
production:
  consumer_key: jwwUeqKRH8fdpgxzMD8xA
  consumer_secret: wjJBWGAXYDzE8Z6V7vHXBiHNixe207HA8yTcILGZw
  oauth_token: 211484270-NviVjsFoo3qja0bswFmBk6CRmBk2yJUQ7T3g5u70
  oauth_token_secret: 4ZV0KS3Ws3lRZvKQxiqgg2cq5BeytRA1fMrMSFx4so
  callback_url: http://herestay.heroku.com/connectors/twitter/callback
